base_url: <%= ENV['BASE_URL'] || 'http://localhost:3000' %>

session:
  key: <%= ENV['SESSION_KEY'] || 'endorwiki.session' %>
  # Make those cookies secure.
  secret: <%= ENV['SESSION_SECRET'] || '69351bf56052f263f3d8fa7f956a05a01ce60a50445ec34cc493698684cd' %>


gollum:
  # The location of the directory where your wiki's repository exists.
  # NOTE: You're responsible for initializing a repository at this
  # location.
  repo_path: <%= ENV['GOLLUM_REPO_PATH'] %>

google:   
  # If a plain OpenID flow is used, require logins from this domain.
  domain: <%= ENV['GOOGLE_AUTH_DOMAIN'] || 'salesforce.com' %>

  # OAuth keys for OAuth based login.
  # If either of these are nil, oAuth2 will not be available.
  oauth2_key: <%= ENV['GOOGLE_OAUTH2_KEY'] %>
  oauth2_secret: <%= ENV['GOOGLE_OAUTH2_SECRET'] %>
  
  

